# Generated by Django 6.1 on 2026-08-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.CharField(choices=[('COLLEGE', '🎓 College Work'), ('HOMEWORK', '📚 Homework'), ('WORK', '💼 Work / Office'), ('PERSONAL', '🏠 Personal'), ('FITNESS', '🏃 Fitness & Health'), ('SHOPPING', '🛒 Shopping / Errand'), ('OTHER', '📌 General / Other')], default='COLLEGE', max_length=20),
        ),
    ]
